default:
  # golem variables
  golem_name: whattemplatemaker
  golem_version: 0.0.0.9000
  app_prod: no

  # number of default rows in the tables
  n_data_rows: 5

  # maximum number of characters in site, feature, and action names
  maximum_name_length: 100

  # table width
  table_width: "100%"

production:
  app_prod: yes

dev:
  golem_wd: !expr here::here()
